pipeline {
agent any
stages {
stage('Build') {
steps {
bat 'd:'
bat '
cd
 D:\17Èí¼ş3\jenkins\.jenkins\workspace/simple-java-
maven
-
app
@script'
bat '
mvn
 -B -DskipTests clean package'
}
}
stage('Test') {
steps {
bat '
mvn
 test'
}
post {
always {
junit
 'target/
surefire
-reports/*.
xml
'
}
}
}
}
}
